mrServiceApp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import register_user, login_user, postServicio, EditView, ListAcabados, ListPlomeria, DetailedView

urlpatterns = [
    path('', views.hola, name='home'),
    path('registrar_usuario/', register_user, name='register_user'),
    path('loguear_usuario/', login_user, name='login_user'),
    path('postServicio/', postServicio.as_view(), name='post_servicio'),

    path('electricidad/', views.Electricidad, name='electricidad'),
    path('deleteElectric/<int:id>', views.EliminarElectricidad, name='deleteElectric'),
    path('pre_eliminar/<int:id>', views.pre_eliminar, name='pre_eliminar'),
    path('edit_post/<int:id>', EditView.as_view(), name='edit_post'),

    path('Listacabados/', views.ListAcabados, name='Listacabados'),
    path('ListPlomeria/', views.ListPlomeria, name='ListPlomeria'),
    path('Listcarpinteria/', views.ListCarpinteria, name='Listcarpinteria'),
    path('detail_view/<int:pk>',DetailedView.as_view(), name='detail_view'),







]

mrServiceProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mrServiceApp.urls')),
    path('',include('django.contrib.auth.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mrServiceApp/models.py
from xxlimited import Null

# Create your models here.
from django.contrib.auth.models import User
from django.db import models


class TipoUsuario(models.Model):
    tipo_usuario = models.CharField(max_length=25, blank=False, null=False)

    def __str__(self):
        return self.tipo_usuario


class Usuario(models.Model):
    nombre = models.CharField(max_length=50)
    apellido = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    tipo_usuario = models.ForeignKey(TipoUsuario, on_delete=models.CASCADE)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombre


class PostServicio(models.Model):
    tipo_servicio = (
        ('Electricidad', 'Electricidad'),
        ('Carpinteria', 'Carpinteria'),
        ('Plomeria', 'Plomeria'),
        ('Acabados', 'Acabados')
    )
    servicio = models.CharField(max_length=20, choices=tipo_servicio)
    descripcion = models.TextField()
    id_usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    num_telefono = models.IntegerField()

    def __str__(self):
        return self.servicio

mrServiceApp/forms.py
from django import forms
from mrServiceApp.models import Usuario, TipoUsuario, PostServicio
from django.contrib.auth.forms import User
from django.contrib.auth.forms import UserCreationForm


class CreateUserForm(UserCreationForm):
    user_name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    first_name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    option = forms.ModelChoiceField(queryset=TipoUsuario.objects.all(),
                                    widget=forms.TextInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['user_name', 'first_name', 'last_name', 'email', 'password1', 'password2', 'option']

    def save(self, commit=True):
        new_user = User.objects.create_user(
            username=self.cleaned_data["user_name"],
            password=self.cleaned_data['password1']
        )
        Usuario.objects.create(
            nombre=self.cleaned_data["first_name"],
            apellido=self.cleaned_data["last_name"],
            email=self.cleaned_data["email"],
            tipo_usuario=self.cleaned_data["option"],
            user=new_user
        )


class formPost(forms.ModelForm):
    tipo_servicio = (
        ('Electricidad', 'Electricidad'),
        ('Carpinteria', 'Carpinteria'),
        ('Plomeria', 'Plomeria'),
        ('Acabados', 'Acabados')
    )
    servicio = forms.ChoiceField(required=True, choices=tipo_servicio)
    descripcion = forms.Textarea()
    id_usuario = forms.ModelChoiceField(queryset=Usuario.objects.all())
    num_telefono = forms.IntegerField(widget=forms.NumberInput())
    class Meta:
        model = PostServicio
        fields = ['servicio', 'descripcion', 'id_usuario','num_telefono']

mrServiceApp/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import permission_required
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView

from .forms import CreateUserForm, formPost
from .models import PostServicio


def register_user(request):
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            # print('paso')
            form.save()
            return redirect('home')
    else:
        form = CreateUserForm()
    context = {'form': form}
    return render(request, 'signup.html', context)


def login_user(request):
    message = ''
    if request.method == 'POST':
        user_name = request.POST['user_name']
        password = request.POST['password']
        user = authenticate(request, username=user_name, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            message = 'Username or password incorrect'

    context = {'message': message}
    return render(request, 'login.html', context)


def hola(request):
    return render(request, 'home.html')


class postServicio(CreateView):
    model = PostServicio
    form_class = formPost
    template_name = 'formularioPost.html'
    context_object_name = 'postear'
    success_url = ('/')


def Electricidad(request):
    data = PostServicio.objects.filter(servicio='Electricidad')
    return render(request, 'electricidad.html', {'data': data})


def EliminarElectricidad(request, id):
    post = PostServicio.objects.get(id=id)
    post.delete()
    post = PostServicio.objects.all()
    return render(request, 'electricidad.html', {'post_delete': post})


def pre_eliminar(request, id):
    return render(request, 'eliminar.html', {'id': id})


class EditView(UpdateView):
    model = PostServicio
    form_class = formPost
    pk_url_kwarg = 'id'
    template_name = 'editarElectricidad.html'
    success_url = ('/')


class DetailedView(DetailView):
    model = PostServicio
    template_name = 'detalle_prestador.html'
    context_object_name = 'post'


'''-------------------------------------------------------------'''


def ListAcabados(request):
    data = PostServicio.objects.filter(servicio='Acabados')
    return render(request, 'ListAcabados.html', {'data': data})


def ListPlomeria(request):
    data = PostServicio.objects.filter(servicio='Plomeria')
    return render(request, 'plomeria.html', {'data': data})


def ListCarpinteria(request):
    data = PostServicio.objects.filter(servicio='Carpinteria')
    return render(request, 'carpinteria.html', {'data': data})

# Create your views here.

templates/ListAcabados.html
{% extends 'base.html' %}
{% load static %}



{% block contenido %}

    <div class="content-wrapper" style="margin-top:80px">
        <div class="container-xxl flex-grow-1 container-p-y">
            <div class="row mb-5">
                {% if data %}
                    {% for item in data %}
                        <br/>
                        <div class="col-md-6 col-lg-4 mb-3">
                            <div class="card h-100">

                                <div class="card-body mt">
                                    <h5 class="card-title">Servicio: {{ item.servicio }}</h5>
                                    <p class="card-text"> Descripcion:
                                        {{ item.descripcion }}
                                    </p>
                                    <p class="card-text"> Prestador:
                                        {{ item.id_usuario }}
                                    </p>

                                    <img class="card-img-top"
                                         src="https://api.lorem.space/image/house?w=150&h=150"
                                         alt="Generic placeholder image" width="140" height="340" alt="Card image>
                                        cap"/>
                                    <hr/>

                                    <div class="mt-3">

                                        {% if perms.mrServiceApp.delete_postservicio %}
                                            <a class="btn btn-danger" href="{% url 'pre_eliminar' item.id %}"
                                               role="button"><i class="tf-icons bx bx-edit"></i>Eliminar</a>
                                        {% endif %}
                                        {% if perms.mrServiceApp.change_postservicio %}
                                            <a class="btn btn-primary" href="{% url 'edit_post' item.id %}"
                                               role="button"><i class="tf-icons bx bx-edit"></i>Editar</a>
                                        {% endif %}


                                        <a class="btn btn-primary" href="{% url 'detail_view' item.id %}"
                                           role="button"><i class="tf-icons bx bx-edit"></i>Contactar</a>

                                    </div>
                                </div>
                            </div>
                        </div>

                    {% endfor %}

                {% else %}
                    <div class="alert alert-warning alert-dismissible" role="alert">
                        This is a warning dismissible alert — check it out!
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="content-backdrop fade"></div>
    </div>

{% endblock %}

templates/addpost.html
{% extends 'base.html' %}
{% load static %}
{% block navbar %}{% endblock %}

{% block contenido %}
    <div class="container pt-5">
        <form method="post" novalidate>
            {% csrf_token %}
         <div class="row">
            <div class="col-md-12">

                <div class="card mb-4">
                    <h5 class="card-header pt-6 background:color-black " >Publicar Post</h5>
                    <div class="card-body">
                        <div>
                            {% for field in form.visible_fields %}
                                <div class="form-group">
                                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                                    {{ field }}
                                    {% for error in field.errors %}
                                        <span class="help-block" style="color:#ff0000">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% endfor %}
                        </div>

                    <button type="submit" class="btn btn-primary mt-lg-2 align-content-end">Publicar</button>
                        <a href="{% url 'listar' %}" class="btn btn-danger mt-lg-2">Cancel</a>
                    </div>
                </div>
            </div>
            </div>
        </form>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Mr.Service</title>

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,700' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/jquery.fancybox.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'css/slit-slider.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="{% static 'js/modernizr-2.6.2.min.js' %}"></script>

</head>

<body id="body">
<!-- preloader -->
<div id="preloader">
    <div class="loder-box">
        <div class="battery"></div>
    </div>
</div>
<!-- end preloader -->

{% block header %}
    <header id="navigation" class="navbar-inverse animated-header">
        <div class="container">
            <div class="navbar-header">
                <!-- responsive nav button -->
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- /responsive nav button -->

                <!-- logo -->
                <h1 class="navbar-brand">
                    <a href="/">MR.SERVICE</a>
                </h1>
                <!-- /logo -->
            </div>

            <!-- main nav -->

            <nav class="collapse navbar-collapse navbar-right">
                <ul class="nav navbar-nav">
                    <li><a href="/#body">Home</a></li>
                    <li><a href="/#service">Categorias</a></li>
                    <li><a href="/#testimonials">Nuestro Equipo</a></li>
                </ul>
                {% if user.is_authenticated %}
                    <a href='{% url 'logout' %}' class="btn btn-blue btn-effect">Logout</a>
                {% endif %}
            </nav>
            <!-- /main nav -->
        </div>
    </header>
{% endblock %}
{% block contenido %}

{% endblock %}

<footer id="footer">
    <div class="container">
        <div class="row text-center">
            <div class="footer-content">
                <div class="wow animated fadeInDown">

                    <div class="footer-social">
                        <ul>
                            <li class="wow animated zoomIn"><a href="#"><i class="fa fa-thumbs-up fa-3x"></i></a></li>
                            <li class="wow animated zoomIn" data-wow-delay="0.3s"><a href="#"><i
                                    class="fa fa-twitter fa-3x"></i></a></li>
                            <li class="wow animated zoomIn" data-wow-delay="0.6s"><a href="#"><i
                                    class="fa fa-skype fa-3x"></i></a></li>
                            <li class="wow animated zoomIn" data-wow-delay="0.9s"><a href="#"><i
                                    class="fa fa-dribbble fa-3x"></i></a></li>
                            <li class="wow animated zoomIn" data-wow-delay="1.2s"><a href="#"><i
                                    class="fa fa-youtube fa-3x"></i></a></li>
                        </ul>
                    </div>

                    <p>Diseñado por el Team Mr.Service -- Proyecto Final Django Básico<a
                            href="http://www.themefisher.com"></a></p>
                </div>
            </div>
        </div>
    </div>
</footer>

<script src="{% static 'js/jquery-1.11.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.singlePageNav.min.js' %}"></script>
<script src="{% static 'js/jquery.fancybox.pack.js' %}"></script>
<script src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.easing.min.js' %}"></script>
<script src="{% static 'js/jquery.slitslider.js' %}"></script>
<script src="{% static 'js/jquery.ba-cond.min.js' %}"></script>
<script src="{% static 'js/wow.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>

</body>
</html>

templates/carpinteria.html
{% extends 'base.html' %}
{% load static %}



{% block contenido %}

 <div class="content-wrapper" style="margin-top:80px">
        <div class="container-xxl flex-grow-1 container-p-y">
            <div class="row mb-5">
                {% if data %}
                    {% for item in data %}
                        <br/>
                        <div class="col-md-6 col-lg-4 mb-3">
                            <div class="card h-100">

                                <div class="card-body mt">
                                    <h5 class="card-title">Servicio: {{item.servicio }}</h5>
                                    <p class="card-text"> Descripcion:
                                        {{ item.descripcion }}
                                    </p>
                                    <p class="card-text"> Prestador:
                                        {{ item.id_usuario }}
                                    </p>

                                     <img class="card-img-top"
                                     src="https://api.lorem.space/image/house?w=150&h=150"
                                     alt="Generic placeholder image" width="140" height="340" alt="Card image>
                                        cap"/>
                                    <hr/>

                                    <div class="mt-3">

                                        {% if perms.mrServiceApp.delete_postservicio %}
                                           <a class="btn btn-danger" href="{% url 'pre_eliminar' item.id%}"
                                               role="button"><i class="tf-icons bx bx-edit"></i>Eliminar</a>
                                        {% endif %}
                                          {% if perms.mrServiceApp.change_postservicio %}
                                           <a class="btn btn-primary" href="{% url 'edit_post' item.id%}"
                                               role="button"><i class="tf-icons bx bx-edit"></i>Editar</a>
                                         {% endif %}

                                            <a class="btn btn-primary" href="{% url 'detail_view' item.id%}"
                                               role="button"><i class="tf-icons bx bx-edit"></i>Contactar</a>

                                    </div>
                                </div>
                            </div>
                        </div>

                    {% endfor %}

                {% else %}
                    <div class="alert alert-warning alert-dismissible" role="alert">
                       <h3>No Hay Datos </h3>
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="content-backdrop fade"></div>
    </div>

{% endblock %}

templates/editar.html
{% extends 'base.html' %}
{% block navbar %}{% endblock %}
{% block Title %} Editar Post {% endblock %}

{% block contenido %}
    <div class="container pt-5">
        <form method="post" novalidate>
            {% csrf_token %}
            <div class="col-md-12">
                <div class="card mb-4">
                    <h5 class="card-header">Editar Anuncio</h5>
                    <div class="card-body">
                        <div>
                            {% for field in form.visible_fields %}
                                <div class="form-group">
                                    <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
                                    {{ field }}
                                    {% for error in field.errors %}
                                        <span class="help-block" style="color:red">{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% endfor %}
                        </div>
                        <button type="submit" class="btn btn-primary mt-lg-2 align-content-end">Editar</button>
                        <a href="{% url 'listar' %}" class="btn btn-danger mt-lg-2">Cancel</a>
                    </div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

templates/electricidad.html
{% extends 'base.html' %}
{% load static %}



{% block contenido %}

    <div class="content-wrapper" style="margin-top:80px">
        <div class="container-xxl flex-grow-1 ">
            <div class="row mb-5">
                {% if data %}
                    {% for item in data %}

                        <div class="col-md-6 col-lg-4 mb-3">
                            <div class="card h-100">
                            <div class="container">
                                <div class="card-body mt">
                                    <h5 class="card-title">Servicio: {{ item.servicio }}</h5>
                                    <p class="card-text"> Descripcion:
                                        {{ item.descripcion }}
                                    </p>
                                    <p class="card-text"> Prestador:
                                        {{ item.id_usuario }}
                                    </p>


                                    <img class="card-img-top"
                                         src="https://api.lorem.space/image/house?w=150&h=150"
                                         alt="Generic placeholder image" width="140" height="340" alt="Card image>
                                        cap"/>
                                    <hr/>

                                    <div class="mt-3">

                                        {% if perms.mrServiceApp.delete_postservicio %}
                                            <a class="btn btn-danger" href="{% url 'pre_eliminar' item.id %}"
                                               role="button"><i class="tf-icons bx bx-edit"></i>Eliminar</a>
                                        {% endif %}
                                        {% if perms.mrServiceApp.change_postservicio %}

                                            <a class="btn btn-primary" href="{% url 'edit_post' item.id %}"
                                               role="butt  on"><i class="tf-icons bx bx-edit"></i>Editar</a>
                                        {% endif %}


                                                <a class="btn btn-primary" href="{% url 'detail_view' item.id %}"
                                                   role="button"><i class="tf-icons bx bx-edit"></i>Contactar</a>
                                            </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                    {% endfor %}

                {% else %}
                    <div class="alert alert-warning alert-dismissible" role="alert">
                       Eliminado
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="content-backdrop fade"></div>
    </div>

{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block header %}
        <div class="container">
    <header  class="navbar-inverse animated-header">

            <div class="navbar-header">
                <!-- logo -->
                <h1 class="navbar-brand">
                    <a href="/#body">MR.SERVICE</a>
                </h1>
                <!-- /logo -->
            </div>


    </header>
      </div>
{% endblock %}
{% block contenido %}

    <div class="container">
        <div class="row">
            <div class="col-md-5 col-md-offset-1">
                <form class="signup-form" method="POST" action="{% url 'login_user' %}">
                    {% csrf_token %}
                    <span class="help-block" style="color:red">{{ form.errors.password }}</span>
                    <h2 class="text-center">Login</h2>

                    <hr>
                    <div class="form-group">

                        <input type="text" class="form-control" placeholder="Nickname" required="required"
                               id="id_user_name"
                               name="user_name">
                    </div>

                    <div class="form-group">

                        <input type="password" class="form-control" placeholder="Confirmacion de contraseña"
                               required="required"
                               id="id_password" name="password">

                    </div>

                    <div class="form-group text-center">

                        <button type="submit" class="btn btn-blue btn-block">Ingresar</button>

                    </div>

                </form>

            </div>
        </div>
    </div>

{% endblock %}

templates/plomeria.html
{% extends 'base.html' %}
{% load static %}



{% block contenido %}

 <div class="content-wrapper" style="margin-top:80px">
        <div class="container-xxl flex-grow-1 container-p-y">
            <div class="row mb-5">
                {% if data %}
                    {% for item in data %}
                        <div class="col-md-6 col-lg-4 mb-3">
                            <div class="card h-100">

                                <div class="card-body mt">
                                    <h5 class="card-title">Servicio: {{item.servicio }}</h5>
                                    <p class="card-text"> Descripcion:
                                        {{ item.descripcion }}
                                    </p>
                                    <p class="card-text"> Prestador:
                                        {{ item.id_usuario }}
                                    </p>

                                     <img class="card-img-top"
                                     src="https://api.lorem.space/image/movie?w=150&amp;amp;amp;amp;h=220"
                                     alt="Generic placeholder image" width="140" height="340" alt="Card image>
                                        cap"/>
                                    <hr/>

                                    <div class="mt-3">

                                        {% if perms.mrServiceApp.delete_postservicio %}
                                           <a class="btn btn-danger" href="{% url 'pre_eliminar' item.id%}"
                                               role="button"><i class="tf-icons bx bx-edit"></i>Eliminar</a>
                                        {% endif %}

                                             {% if perms.mrServiceApp.change_postservicio %}

                                           <a class="btn btn-primary" href="{% url 'edit_post' item.id%}"
                                               role="button"><i class="tf-icons bx bx-edit"></i>Editar</a>
                                                 {% endif %}

                                            <a class="btn btn-primary" href="{% url 'detail_view' item.id%}"
                                               role="button"><i class="tf-icons bx bx-edit"></i>Contactar</a>

                                    </div>
                                </div>
                            </div>
                        </div>

                    {% endfor %}

                {% else %}
                    <div class="alert alert-warning alert-dismissible" role="alert">
                        This is a warning dismissible alert — check it out!
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="content-backdrop fade"></div>
    </div>

{% endblock %}

templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block header %}
    <header id="navigation" class="navbar-inverse animated-header">
        <div class="container">
            <div class="navbar-header">

                <!-- logo -->
                <h1 class="navbar-brand">
                    <a href="/">MR.SERVICE</a>
                </h1>
                <!-- /logo -->
            </div>

        </div>
    </header>
{% endblock %}
{% block contenido %}

    <div class="container">
        <div class="row">
            <div class="col-md-5 col-md-offset-1">

                <form class="signup-form" method="POST" action="{% url 'register_user' %}">
                    {% csrf_token %}
                    <span class="help-block" style="color:red">{{ form.errors.password }}</span>
                    <h2 class="text-center">Formulario de registro</h2>

                    <hr>

                    <div class="form-group">

                        <input type="text" class="form-control" placeholder="Nickname" required="required"
                               id="id_user_name"
                               name="user_name">

                    </div>

                    <div class="form-group">

                        <input type="text" class="form-control" placeholder="Nombres" required="required"
                               id="id_first_name"
                               name="first_name">

                    </div>

                    <div class="form-group">

                        <input type="text" class="form-control" placeholder="Apellidos" required="required"
                               id="id_last_name" name="last_name">

                    </div>

                    <div class="form-group">

                        <input type="email" class="form-control" placeholder="Correo" required="required" id="id_email"
                               name="email">

                    </div>

                    <div class="form-group">

                        <input type="password" class="form-control" placeholder="Contraseña" required="required"
                               id="id_password1" name="password1">

                    </div>

                    <div class="form-group">

                        <input type="password" class="form-control" placeholder="Confirmacion de contraseña"
                               required="required"
                               id="id_password2" name="password2">

                    </div>

                    <select class="form-select form-select-lg mb-2 form-group form-control"
                            aria-label=".form-select-lg example" id="id_option" name="option">
                        <option selected>Seleccione rol</option>
                        <option value="1">Cliente</option>
                        <option value="2">Prestador de Servicios</option>
                    </select>

                    <div class="form-group text-center">

                        <button type="submit" class="btn btn-blue btn-block">Registrarse</button>

                    </div>

                </form>

            </div>
        </div>
    </div>

{% endblock %}